version: '3.8'
services:
  nextcloud:
    container_name: yuuyu-Nextcloud
    image: nextcloud:fpm-alpine
    volumes:
      - ./data/nextcloud:/var/www/html
      - ${DATA_DIR}:/var/www/html/data
    depends_on:
      - redis
    networks:
      - yuuyu-network
      - yuuyu-nextcloud-network
    environment:
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_UPDATE=1
    restart: always
  nginx:
    container_name: yuuyu-Nextcloud-Nginx
    image: nginx:stable-alpine
    volumes:
      - ./data/nextcloud:/var/www/html:ro
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud
    networks:
      - yuuyu-network
      - yuuyu-nextcloud-network
    restart: always
  cron:
    container_name: yuuyu-Nextcloud-Cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
      - ${DATA_DIR}:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - redis
    networks:
      - yuuyu-network
      - yuuyu-nextcloud-network
  redis:
    container_name: yuuyu-Nextcloud-Redis
    image: redis:alpine
    volumes:
      - ./dara/redis/data:/data
    networks:
      - yuuyu-nextcloud-network
    restart: always
networks:
  yuuyu-nextcloud-network:
  yuuyu-network:
    external: true
